apiVersion: presentations.haavard.dev/v1alpha1
kind: Presentation
metadata:
  name: presentation-sample
spec:
  slides:
    - title: "Operator-sdk: Why and how to make custom resources"
    - title: "Kubernetes re-cap"
      bullets:
        - Orchestrator
        - Microservices
        - Apply resources/workloads with yaml specs
        - Services, deployments, ingress
        - GitOps
    - images:
        - https://cdn.prod.website-files.com/5ff66329429d880392f6cba2/673f4107a915916cd43fbdf8_646786e5646162c532696293_661.2.jpeg
    - title: "Operator pattern"
      images:
        - "https://iximiuz.com/kubernetes-operator-pattern/kube-control-loop-3000-opt.png"
    - title: "Custom resources (CRDs)"
      bullets:
        - Extension of kubernetes' operators and their API
        - Defines the interface of what an object should look like.
        - Controller/operator reacts to objects
    - title: "Example"
      images:
        - https://i.imgur.com/JPhVHMw.png
    - title: "Operator SDK"
      bullets:
        - Tooling/framework for developing operators
        - CLI for handling boilerplate
        - Reconcilliation loop written in golang
