apiVersion: presentations.haavard.dev/v1alpha1
kind: Presentation
metadata:
  name: presentation-sample
spec:
  slides:
    - title: "Kubernetes re-cap"
      bullets:
        - Orchestrator
        - Microservices
        - Apply resources/workloads with yaml specs
        - Services, deployments, ingress
        - GitOps
    - title: "Kubernetes re-cap"
      bullets:
        - use e.g. argoCD to continuously apply resources defined in GitOps repository
    - title: "Kubernetes re-cap"
      images:
        - https://kubernetes.io/images/docs/components-of-kubernetes.svg

    - title: "Operator pattern?"
      images:
        - "https://iximiuz.com/kubernetes-operator-pattern/kube-control-loop-3000-opt.png"
