apiVersion: presentations.haavard.dev/v1alpha1
kind: Presentation
metadata:
  name: presentation-sample
spec:
  slides:
    - title: "Kubernetes re-cap"
      bullets:
        - Orchestrator
        - Microservices
        - Apply resources/workloads with yaml specs
        - Services, deployments, ingress
        - GitOps
        - use e.g. argoCD to continuously apply resources defined in GitOps repository
        - Kubernetes has controllers that reads the resource manifests, reacts and updates the cluster accordingly

    - title: "What is the operator pattern?"
      bullets:
        - Encapsulates operational logic
      images:
        - "https://iximiuz.com/kubernetes-operator-pattern/kube-control-loop-3000-opt.png"
