apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
        - image: app
          name: app
