namePrefix: slide-controller-
resources:
- deployment.yaml

kind: Kustomization
images:
- name: app
  newName: ghcr.io/operator-sdk-demo/slide-controller
  newTag: d90f12409ca29dc8773056a74abe1b8ae50266c6
apiVersion: kustomize.config.k8s.io/v1beta1
