resources:
- deployment.yaml
- rbac
- crd

kind: Kustomization
images:
- name: app
  newName: ghcr.io/operator-sdk-demo/slide-controller
  newTag: 0e9241bfb20ea32aec06d63268f8f0a158161cb2
apiVersion: kustomize.config.k8s.io/v1beta1
